version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/exercisefiles/javascript/"
      - "/exercisefiles/typescript/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "/exercisefiles/go/"
      - "/exercisefiles/devops/terraform/aws/test"
      - "/exercisefiles/devops/terraform/azure/test"   
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/exercisefiles/python/"
      - "/exercisefiles/data_engineering/"   
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directories:
      - "/exercisefiles/java/quarkus/"
      - "/exercisefiles/java/springboot/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
    - "/exercisefiles/dotnet/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "composer"
    directories:
    - "/exercisefiles/php/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"