version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/exercisefiles/node/"
      - "/exercisefiles/node_typescript/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directories:
      - "/exercisefiles/python/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directories:
      - "/exercisefiles/java_quarkus/"
      - "/exercisefiles/java_springboot/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
    - "/exercisefiles/dotnet/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "dotnet-sdk"
    directories:
    - "/exercisefiles/dotnet/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"